### ISSUE TITLE
Merge language aliases

### ISSUE THREAD

**Issue by grant** [xkxx/throwtable#11]
Many implementations have different language names for the same semantic language. For example:

'js', 'Javascript', 'JavaScript'
'c sharp|C#', 'C sharp', 'C#'
'Bash', 'bash'

Can we normalize this to some common name? At least fix javascript.

**Comment by MinjingZhu** [comment]
Could you restore dumps version 3.2 and see if it is fixed thoroughly?

**Comment by grant** [comment]
```
/usr/local/lib/node_modules/elasticdump/node_modules/line-reader/lib/line_reader.js:108
        throw err;
        ^

Error: ENOENT: no such file or directory, open 'elasticsearch_algorithm_v3.0.json'
    at Error (native)
Mon, 14 Dec 2015 19:02:56 GMT | starting dump
/usr/local/lib/node_modules/elasticdump/node_modules/line-reader/lib/line_reader.js:108
        throw err;
        ^

Error: ENOENT: no such file or directory, open 'elasticsearch_category_v3.0.json'
    at Error (native)
Mon, 14 Dec 2015 19:02:56 GMT | starting dump
/usr/local/lib/node_modules/elasticdump/node_modules/line-reader/lib/line_reader.js:108
        throw err;
        ^

Error: ENOENT: no such file or directory, open 'elasticsearch_implementation_v3.0.json'
    at Error (native)
```

Did you test the restore script?

**Comment by grant** [comment]
@MinjingZhu Doesn't seem to have an affect.

**Comment by MinjingZhu** [comment]
@grant I pushed again. It should work this time :) Could you pull and restore v3.2 again?
Also, I noticed that all the 'js' ones come from npm, and I don't have control on it,
so after you restore dumps, run a redis server in any folder, and then run AlgorithmNames/impl_languages_deduplication.py
It will do deduplication on your current elasticsearch database.

**Comment by grant** [comment]
How do you start that python script?

```
granttimmerman:AlgorithmNames$ python impl_languages_deduplication.py
Traceback (most recent call last):
  File "impl_languages_deduplication.py", line 1, in <module>
    from elasticsearch import Elasticsearch
ImportError: No module named elasticsearch
```

**Comment by grant** [comment]
Can you just check on your end?

**Comment by MinjingZhu** [comment]
Did you install the python driver of elasticsearch?

**Comment by grant** [comment]
I don't know how to do that. Can you add instructions to the README or here?

**Comment by grant** [comment]
I'll close assuming @xkxx is working on merging JavaScript and js.
